name: Release

on:
  workflow_run:
    workflows: [ Test ]
    branches: [ main ]
    types: 
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.x'

      - name: Delete Old Release
        uses: actions/github-script@v3
        with:
          script: |
            let release
            try {
              release = await github.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: 'v1.0'
              })
            } catch(e) {
              console.error(e)
              return
            }

            await github.repos.deleteRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id
            })

            await github.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/v1.0'
            })

      - name: Build
        id: build
        run: |
          npm i --no-package-lock
          npm run build
          go mod download
          go build -ldflags "-s -w"
          GOOS=windows go build -ldflags "-s -w"
          tar cvzf release.tar.gz public scripts myvideo config.ini.default
          zip -9vr release-windows.zip public scripts myvideo.exe config.ini.default
          echo "::set-output name=date::$(TZ=CST date +'%Y-%m-%d')"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0
          name: ${{ steps.build.outputs.date }}
          body: ${{ steps.build.outputs.date }}
          files: |
            release.tar.gz
            release-windows.zip
