name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '15'

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.x'

      - name: Test Code
        run: |
          npm i --no-package-lock
          npm run build
          go mod download
          go build -v ./...
